# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
static/frame-openapi.json:
  spec:
    - '#/info/license'
  operation-operationId-unique:
    - >-
      #/paths/~1v4~1accounts~1{account_id}~1comments~1{comment_id}/patch/DeveloperApiWeb.CommentsController.update
  no-unresolved-refs:
    - '#/components/schemas/Asset/discriminator/mapping/file'
    - '#/components/schemas/Asset/discriminator/mapping/folder'
    - '#/components/schemas/Asset/discriminator/mapping/version_stack'
    - '#/components/schemas/CustomField/discriminator/mapping/date'
    - '#/components/schemas/CustomField/discriminator/mapping/long_text'
    - '#/components/schemas/CustomField/discriminator/mapping/number'
    - '#/components/schemas/CustomField/discriminator/mapping/rating'
    - '#/components/schemas/CustomField/discriminator/mapping/select'
    - '#/components/schemas/CustomField/discriminator/mapping/select_multi'
    - '#/components/schemas/CustomField/discriminator/mapping/text'
    - '#/components/schemas/CustomField/discriminator/mapping/toggle'
    - '#/components/schemas/CustomField/discriminator/mapping/users'
    - '#/components/schemas/AssetWithIncludes/discriminator/mapping/file'
    - '#/components/schemas/AssetWithIncludes/discriminator/mapping/folder'
    - '#/components/schemas/AssetWithIncludes/discriminator/mapping/version_stack'
  spec-components-invalid-map-name:
    - '#/components/schemas/Collection Include'
    - '#/components/schemas/Asset Include'
    - '#/components/schemas/Children Type'
    - '#/components/schemas/Project Include'
    - '#/components/schemas/Comment Include'
  security-defined:
    - '#/security/0/Authorization'
